spring.application.name=edulearn-web
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# Eureka
eureka.client.service-url.defaultZone=http://admin:edulearn123@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Microservice URLs
auth.service.url=http://localhost:8081
course.service.url=http://localhost:8082
enrollment.service.url=http://localhost:8083
assessment.service.url=http://localhost:8084
payment.service.url=http://localhost:8085
progress.service.url=http://localhost:8086
discnotif.service.url=http://localhost:8087

# File upload limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Session
server.servlet.session.timeout=86400s
