spring.application.name=ai-service
server.port=8095

# Eureka Configuration
eureka.client.service-url.defaultZone=http://admin:edulearn123@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# AI Configuration (Placeholders)
google.gemini.api.key=AIzaSyCvkWl4fnW4oY9dK4qx82GDDwNKIr0Xico
# AIzaSyBK8Eq3myGCGR6DjrDXsYU6SHrHAS6iEWA
google.gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
