server.port=8090
spring.application.name=certificate-service
spring.datasource.url=jdbc:h2:mem:certdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
management.endpoints.web.exposure.include=*
eureka.client.service-url.defaultZone=http://admin:edulearn123@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

certificate.output-dir=certificates/
certificate.verify-base-url=http://localhost:8765/api/certificates/verify
